//
//  VSCSoundSourceGenerator.h
//  SynthStation
//
//  Created by Jonathan Thorpe on 06/11/2011.
//  Copyright 2011 NXP. All rights reserved.
//

#import <Cocoa/Cocoa.h>

#import "Stk.h"
#import "VSCSynthSourceGenerator.h"
#import "VSCSoundParameterViewProtocol.h"

//@class VSCSoundParameterView;
//@class VSCSoundChannelLevelParameterView;

@interface VSCSoundSourceGeneratorDebugView : NSView {
	
	VSCSynthSourceGeneratorPtr sourceGenerator;
	
	NSTextField* generatorTitleTextField;
	NSTextField* tickCountTextField;
	NSButton* tickButton;
	
	/*
	 *	This table view is used to display the tick data generated by the 
	 *	generator, the last tickDepth frames will be shown in the NSTableView
	 */
	NSTableView* tickTableView;
	NSInteger tickDepth;
	stk::StkFrames tickFrames;
	
	/*
	 *	As for the generatorParameterView, the class of the channelLevelParameterView
	 *  is left to be determined at runtime by subclasses for maximum flexibility.
	 */
	NSView* channelLevelParameterParentView;
	NSView<VSCSoundParameterViewProtocol>* channelLevelParameterView;
	
	/*
	 *	In order to allow the configuration of the generator parameter view into any subclass
	 *	of VSCSoundParameter view, we have a generatorParameterParentView which is loaded
	 *	from nib to which we add a parameter control view of some sort
	 *	created dynamically by subclasses of this class.
	 */
	NSView* generatorParameterParentView;
	NSView<VSCSoundParameterViewProtocol>* generatorParameterView;

}

@property (nonatomic, assign) NSInteger tickDepth;

@property (nonatomic, retain) IBOutlet NSTextField* generatorTitleTextField;
@property (nonatomic, retain) IBOutlet NSTextField* tickCountTextField;

@property (nonatomic, retain) IBOutlet NSButton* tickButton;
@property (nonatomic, retain) IBOutlet NSTableView* tickTableView;

@property (nonatomic, retain) IBOutlet NSView* channelLevelParameterParentView;
@property (nonatomic, retain) IBOutlet NSView* generatorParameterParentView;

@property (nonatomic, retain) NSView<VSCSoundParameterViewProtocol>* channelLevelParameterView;
@property (nonatomic, retain) NSView<VSCSoundParameterViewProtocol>* generatorParameterView;

-(IBAction) tickButtonClicked:(id)sender;

/*
 *	Custom initialization, particularly creating the approproate control subview for
 *	generatorControlParentView.
 */
-(void) customInit;
-(void) createChannelLevelParameterView;
-(void) createGeneratorParameterView;

/*
 *	C++ Setters/Getters
 */
-(VSCSynthSourceGeneratorPtr) getSourceGenerator;
-(void) setSourceGenerator:(VSCSynthSourceGeneratorPtr)_sourceGenerator;

/*
 *	Get a copy of the current tickFrames
 */
-(stk::StkFrames) tickFramesCopy;

@end
