//
//  VSCSoundSourceGenerator.h
//  SynthStation
//
//  Created by Jonathan Thorpe on 06/11/2011.
//  Copyright 2011 NXP. All rights reserved.
//

#import <Cocoa/Cocoa.h>

#import "Stk.h"
#import "VSCSoundGenerator.h"
#import "VSCSoundElementView.h"


/*
 *	I don't think this view should be subclassed as it is only a wrapper for a VSCSoundParameterView
 *	
 */

@interface VSCSoundSourceGeneratorDebugView : VSCSoundElementView {
	
	NSTextField* generatorTitleTextField;
	NSTextField* tickCountTextField;
	NSButton* tickButton;
	
	/*
	 *	This table view is used to display the tick data generated by the 
	 *	generator, the last tickDepth frames will be shown in the NSTableView
	 */
	NSTableView* tickTableView;

}

@property (nonatomic, assign) NSInteger tickDepth;

@property (nonatomic, retain) IBOutlet NSTextField* generatorTitleTextField;
@property (nonatomic, retain) IBOutlet NSTextField* tickCountTextField;

@property (nonatomic, retain) IBOutlet NSButton* tickButton;
@property (nonatomic, retain) IBOutlet NSTableView* tickTableView;


-(void) setSynthSourceGenerator:(VSCSoundGeneratorPtr)generator;
-(VSCSoundGeneratorPtr) getSoundElement;


-(IBAction) tickButtonClicked:(id)sender;

/*
 *	Custom initialization, particularly creating the approproate control subview for
 *	generatorControlParentView.
 */
-(void) customInit;


@end
